"""empty message

Revision ID: 86b0dab1ca6b
Revises: 
Create Date: 2026-03-06 21:29:31.930155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86b0dab1ca6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('NAME'))

    op.drop_table('schools')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('users')
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('NAME'))

    op.drop_table('provinces')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('NAME', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='省份名称'),
    sa.Column('school_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='所属影系ID'),
    sa.Column('region', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='流行地区'),
    sa.Column('shape_features', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='造型特色'),
    sa.Column('color_features', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='色彩特色'),
    sa.Column('singing_features', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='唱腔特色'),
    sa.Column('representative_plays', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='代表剧目'),
    sa.Column('image1', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='图片1路径'),
    sa.Column('image2', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='图片2路径'),
    sa.Column('image3', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='图片3路径'),
    sa.Column('image4', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='图片4路径'),
    sa.Column('image5', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='图片5路径'),
    sa.Column('image6', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='图片6路径'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('provinces_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('NAME'), ['NAME'], unique=True)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('schools',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('NAME', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='影系名称'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('NAME'), ['NAME'], unique=True)

    # ### end Alembic commands ###
