"""add avatar_url to users

Revision ID: a245e5ced8ac
Revises: 86b0dab1ca6b
Create Date: 2026-03-18 21:10:21.126941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a245e5ced8ac'
down_revision = '86b0dab1ca6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.alter_column('region',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='流行地区',
               existing_nullable=True)
        batch_op.alter_column('shape_features',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='造型特色',
               existing_nullable=True)
        batch_op.alter_column('color_features',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='色彩特色',
               existing_nullable=True)
        batch_op.alter_column('singing_features',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='唱腔特色',
               existing_nullable=True)
        batch_op.alter_column('representative_plays',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='代表剧目',
               existing_nullable=True)
        batch_op.alter_column('image1',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='图片1路径',
               existing_nullable=True)
        batch_op.alter_column('image2',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='图片2路径',
               existing_nullable=True)
        batch_op.alter_column('image3',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='图片3路径',
               existing_nullable=True)
        batch_op.alter_column('image4',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='图片4路径',
               existing_nullable=True)
        batch_op.alter_column('image5',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='图片5路径',
               existing_nullable=True)
        batch_op.alter_column('image6',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='图片6路径',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('school_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='所属影系ID',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('NAME'))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint(batch_op.f('provinces_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'schools', ['school_id'], ['id'])
        batch_op.drop_column('NAME')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('NAME')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NAME', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='影系名称'))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NAME', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='省份名称'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('provinces_ibfk_1'), 'schools', ['school_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('NAME'), ['NAME'], unique=True)
        batch_op.alter_column('school_id',
               existing_type=mysql.INTEGER(),
               comment='所属影系ID',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('image6',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='图片6路径',
               existing_nullable=True)
        batch_op.alter_column('image5',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='图片5路径',
               existing_nullable=True)
        batch_op.alter_column('image4',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='图片4路径',
               existing_nullable=True)
        batch_op.alter_column('image3',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='图片3路径',
               existing_nullable=True)
        batch_op.alter_column('image2',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='图片2路径',
               existing_nullable=True)
        batch_op.alter_column('image1',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='图片1路径',
               existing_nullable=True)
        batch_op.alter_column('representative_plays',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='代表剧目',
               existing_nullable=True)
        batch_op.alter_column('singing_features',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='唱腔特色',
               existing_nullable=True)
        batch_op.alter_column('color_features',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='色彩特色',
               existing_nullable=True)
        batch_op.alter_column('shape_features',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='造型特色',
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='流行地区',
               existing_nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
